name: Python Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Test with unittest
      run: |
        python -m unittest dockertest.py
    - name: Lint with Pylint
      run: |
        python -m pylint dockertest.py
